### ISSUE TITLE
Intel cards query

### ISSUE THREAD

**Issue by adw555** [snabbco/snabb#1160]
Hi,
I'd like to test snabb with kernal-passthrough and was wondering if I was to purchase an HP branded Intel i210 NIC, would this be supported or must it be an actual Intel card? (https://www.amazon.co.uk/d/34m/Intel-I210-T1-Network-adapter-Express-profile-Ethernet/B00ESFF2JC)
Thanks

**Comment by petebristow** [comment]
Looking at my Amazon order history that's the card I developed the driver
against, so yes it should work.

Pete

**Comment by adw555** [comment]
Many Thanks Peter.
