### ISSUE TITLE
Windows Version?

### ISSUE THREAD

**Issue by lonnietc** [snabbco/snabb#1520]
Hello,

I am interested in a cross-platform performant vSwitch and came across SNABB.

As it is based upon LuaJIT, I was wondering if there is a Windows 10 (x64) version as well?

Thanks and have a great day

**Comment by lonnietc** [comment]
Hello,

Is there any update to this as I am very eager to try Snabb on Windows, if at all possible?

Thanks

**Comment by eugeneia** [comment]
Hey, sorry, I didn't see this earlier. Supporting other operating systems is out of scope for Snabb. I recommend a re-implementation instead, such as https://github.com/eugeneia/rush

**Comment by lonnietc** [comment]
Thanks for  the link and I will look into it more.
