### ISSUE TITLE
Troubleshooting/performance should be better documented

### ISSUE THREAD

**Issue by kbara** [snabbco/snabb#741]
I read Luke's comment on a single API manual ( https://github.com/SnabbCo/snabbswitch/issues/733#issuecomment-179634478 ) and think he's right. I also think a single manual would be good for cross-Snabb-application troubleshooting/performance tweaking. It should cover things like not receiving packets due to IOMMU settings, numactl+taskset, etc.

**Comment by eugeneia** [comment]
#824 might be related.

**Comment by wingo** [comment]
cc @kbara for her recent document where she pulled in some machine-level performance tuning suggestions from @mwiget

**Comment by wingo** [comment]
Haha, I neglected to see that the ticket was made by @kbara :)  Ignore me please :)

**Comment by eugeneia** [comment]
#827

**Comment by eugeneia** [comment]
Closing because #827 was merged, please reopen on demand.
