### ISSUE TITLE
Compile on 32 bit system

### ISSUE THREAD

**Issue by jhonan** [snabbco/snabb#79]
I had to make some small mods to compile on 32 bit.

diff --git a/src/apps/vhost/vhost_client.c b/src/apps/vhost/vhost_client.c
index 31f3c77..19690a7 100644
--- a/src/apps/vhost/vhost_client.c
+++ b/src/apps/vhost/vhost_client.c
@@ -53,10 +53,10 @@ static int setup_vring(struct vhost *vhost, int index)
   struct vhost_vring_file  kick = { .index = index, .fd = vring->kickfd };
   struct vhost_vring_file  call = { .index = index, .fd = vring->callfd };
   struct vhost_vring_addr  addr = { .index = index,
-                                    .desc_user_addr  = (uint64_t)&vring->desc,
-                                    .avail_user_addr = (uint64_t)&vring->avail,
-                                    .used_user_addr  = (uint64_t)&vring->used,
-                                    .log_guest_addr  = (uint64_t)NULL,
-                                    .desc_user_addr  = (intptr_t)&vring->desc,
-                                    .avail_user_addr = (intptr_t)&vring->avail,
-                                    .used_user_addr  = (intptr_t)&vring->used,
- ```
                                 .log_guest_addr  = (intptr_t)NULL,
                               .flags = 0 };
  ```
  
  return (ioctl(vhost->vhostfd, VHOST_SET_VRING_NUM,  &num)  ||
         ioctl(vhost->vhostfd, VHOST_SET_VRING_BASE, &base) ||
  diff --git a/src/core/memory.c b/src/core/memory.c
  index c27de86..417f770 100644
  --- a/src/core/memory.c
  +++ b/src/core/memory.c
  @@ -5,6 +5,7 @@
  # include <stdio.h>
  # include <sys/mman.h>
  # include <sys/types.h>
  
  +#include <inttypes.h>
  # include <unistd.h>
  
  /// ### HugeTLB page allocation
  @@ -55,7 +56,7 @@ uint64_t phys_page(uint64_t virt_page)
   return 0;
  }
  if ((data & (1ULL<<63)) == 0) {
-    fprintf(stderr, "page %lx not present: %lx", virt_page, data);
-    fprintf(stderr, "page %" PRIX64 " not present: %" PRIX64, virt_page, data);
   return 0;
  }
  return data & ((1ULL << 55) - 1);
  diff --git a/src/lib/hardware/vfio.c b/src/lib/hardware/vfio.c
  index 1d5345a..81050d2 100644
  --- a/src/lib/hardware/vfio.c
  +++ b/src/lib/hardware/vfio.c
  @@ -88,7 +88,7 @@ uint64_t mmap_memory(void *buffer, uint64_t size, uint64_t iova, uint8_t read, u
  
   struct vfio_iommu_type1_dma_map dma_map = { .argsz = sizeof(dma_map) };
-    dma_map.vaddr = (uint64_t)buffer;
-    dma_map.vaddr = (intptr_t)buffer;
   dma_map.size = size;
   dma_map.iova = iova;
   dma_map.flags = 0 |

**Comment by PrimeEuler** [comment]
Any more work done on a 32bit compile? I'd love to get this switch operational on a beaglebone or rasberry pi running ubuntu.
