### ISSUE TITLE
how to parse http?

### ISSUE THREAD

**Issue by heijiu** [snabbco/snabb#860]
how to parse http?
how to include libhtp?
and include fast regex engine?
thanks

**Comment by eugeneia** [comment]
I am afraid I do not understand your questions in context of Snabb. What exactly are you trying to do?

**Comment by heijiu** [comment]
I want custom a web Application Firewall

**Comment by lukego** [comment]
Snabb is probably more low-level than what you are looking for. I would suggest checking out [OpenResty](https://openresty.org/en/).

**Comment by eugeneia** [comment]
@heijiu I am closing this because I do not think this issue is particularly related to Snabb.
