### ISSUE TITLE
Ingress drop counter for Intel10G not working for vmdq=true

### ISSUE THREAD

**Issue by wingo** [snabbco/snabb#924]
Garrr, there is a limitation in #909 -- it works fine for 82599 cards in single-function mode, but in VF mode it doesn't work unless you pass `rxcounter=0` in the app config.  This is because in VF mode we need to map virtual statistics to one of the global statistics counters, which are scarce relative to the number of possible VF's.

I propose to default `rxcounter` and `txcounter` to 0 if they are not set for `vmdq=true`.  WDYT @eugeneia @mwiget @dpino @lukego ?

**Comment by wingo** [comment]
This is an instance of the class of bugs also including #749.  Of course the fix here will be more limited.

**Comment by eugeneia** [comment]
I think your proposal is sensible. :+1: The limited per-queue statistics register arrays of the 82599 are a constant culprit for me as well...
